swagger: "2.0"
info:
  description: This is the swagger file accompanying server code
  version: "1.0.0"
  title: Yahtzee REST API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by server application
paths:
  /users:
    get:
      operationId: "users.read"
      tags:
        - "Users"
      summary: "The users data structure supported by the application"
      description: "Read the list of users"
      responses:
        200:
          description: "Successful read users list operation"
          schema:
            type: "array"
            items:
              properties:
                first_name:
                  type: "string"
                last_name:
                  type: "string"
                username:
                  type: "string"
                email:
                  type: "string"
                timestamp:
                  type: "string"
