swagger: "2.0"
info:
  description: This is the swagger file accompanying server code
  version: "1.0.0"
  title: Yahtzee REST API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api/v1"

# Paths supported by server application
paths:
  /users:
    get:
      operationId: "yahtzee.users.read_all"
      tags:
        - "Users"
      summary: "Read the entire set of users, sorted by last name"
      description: "Read the entire set of users, sorted by last name"
      responses:
        200:
          description: "Successful read users list operation"
          schema:
            type: "array"
            items:
              properties:
                username:
                  type: "string"
                  description: "username of the user"
                first_name:
                  type: "string"
                  description: "first name of the user"
                last_name:
                  type: "string"
                  description: "last name of the user"
                email:
                  type: "string"
                  description: "email of the user"
                timestamp:
                  type: "string"
                  description: "time stamp of creating/updating user"
